# Generated by Django 3.2.6 on 2021-08-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='available',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.slot'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='bank',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.bankaccount'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='dp',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
