# Generated by Django 3.2.6 on 2021-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timing',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
