# Generated by Django 3.2.6 on 2021-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210811_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addr1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='acc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='ifsc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pan',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
