# Generated by Django 3.2.6 on 2021-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210811_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.AlterField(
            model_name='slot',
            name='fromt',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='to',
            field=models.TimeField(blank=True),
        ),
    ]
