# Generated by Django 3.2.6 on 2021-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210812_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='visitor',
        ),
        migrations.AddField(
            model_name='booking',
            name='visitor',
            field=models.ManyToManyField(to='authentication.Visitor'),
        ),
    ]
