# Generated by Django 3.2.6 on 2021-08-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210811_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='available',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='authentication.slot'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='bank',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='authentication.bankaccount'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='authentication.address'),
        ),
    ]
