# Generated by Django 3.2.6 on 2021-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210811_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='visitor',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
